### ISSUE TITLE
installing on raspberry pi. compile errors

### ISSUE THREAD

**Issue by paddywwoof** [carsales/pyheif#26]
Hi, I've installed and run this on ubuntu fine but having problems on Rasberry Pi. The dependencies seem to be there but the tokens in your heif.h file don't seem to be picked up. Hopefully this is something simple I'm missing out.

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyheif
  Using cached https://files.pythonhosted.org/packages/a0/b5/74e08a65b3775153f72b2bf75adf9ca48f41db207e0d21dd7c8876e413cb/pyheif-0.5.1.tar.gz
Requirement already satisfied: cffi>=1.0.0 in ./.local/lib/python3.7/site-packages (from pyheif) (1.14.2)
Requirement already satisfied: pycparser in ./.local/lib/python3.7/site-packages (from cffi>=1.0.0->pyheif) (2.20)
Building wheels for collected packages: pyheif
  Running setup.py bdist_wheel for pyheif: started
  Running setup.py bdist_wheel for pyheif: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-gtwqgz5p/pyheif/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-gpqdg37p --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  creating build/lib.linux-armv7l-3.7/pyheif
  copying pyheif/error.py -> build/lib.linux-armv7l-3.7/pyheif
  copying pyheif/constants.py -> build/lib.linux-armv7l-3.7/pyheif
  copying pyheif/__init__.py -> build/lib.linux-armv7l-3.7/pyheif
  copying pyheif/reader.py -> build/lib.linux-armv7l-3.7/pyheif
  copying pyheif/writer.py -> build/lib.linux-armv7l-3.7/pyheif
  creating build/lib.linux-armv7l-3.7/pyheif/data
  copying pyheif/data/version.txt -> build/lib.linux-armv7l-3.7/pyheif/data
  running build_ext
  generating cffi module 'build/temp.linux-armv7l-3.7/_libheif_cffi.c'
  creating build/temp.linux-armv7l-3.7
  building '_libheif_cffi' extension
  creating build/temp.linux-armv7l-3.7/build
  creating build/temp.linux-armv7l-3.7/build/temp.linux-armv7l-3.7
  arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include -I/usr/include/python3.7m -c build/temp.linux-armv7l-3.7/_libheif_cffi.c -o build/temp.linux-armv7l-3.7/build/temp.linux-armv7l-3.7/_libheif_cffi.o
  build/temp.linux-armv7l-3.7/_libheif_cffi.c: In function ‘_cffi_const_heif_unknown_brand’:
  build/temp.linux-armv7l-3.7/_libheif_cffi.c:836:12: error: ‘heif_unknown_brand’ undeclared (first use in this function)
     int n = (heif_unknown_brand) <= 0;
              ^~~~~~~~~~~~~~~~~~
  build/temp.linux-armv7l-3.7/_libheif_cffi.c:836:12: note: each undeclared identifier is reported only once for each function it appears in
  build/temp.linux-armv7l-3.7/_libheif_cffi.c: In function ‘_cffi_const_heif_heic’:
  build/temp.linux-armv7l-3.7/_libheif_cffi.c:843:12: error: ‘heif_heic’ undeclared (first use in this function); did you mean ‘heif_writer’?
     int n = (heif_heic) <= 0;
              ^~~~~~~~~
              heif_writer
  build/temp.linux-armv7l-3.7/_libheif_cffi.c: In function ‘_cffi_const_heif_heix’:
### etc etc for all the constants
```

**Comment by david-poirier-csn** [comment]
You'll need to install the latest `libheif` from source before install pyheif.

**Comment by paddywwoof** [comment]
@david-poirier-csn thanks. I interpreted "latests libheif from source" as download v1.8 source from github and
```
sudo apt install autotools-dev
sudo apt install automake
sudo apt install libtool
./autogen.sh
./configure
make
sudo make install
```
(most of which had to be discovered by trial and error/google) Now I can ```pip3 install pyheif --user``` (and I also downloaded the repo from here and ```sudo python3 setup.py install```) but I get
```
>>> import pyheif
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/pyheif/pyheif/__init__.py", line 3, in <module>
    import _libheif_cffi
ImportError: /home/pi/.local/lib/python3.7/site-packages/_libheif_cffi.abi3.so: undefined symbol: heif_image_handle_get_raw_color_profile
>>> 
```
Is there some other header I need to install?

**Comment by david-poirier-csn** [comment]
If you download the release you should be able to skip `autogen.sh` and most of the dependencies.

Try running `./configure -prefix /usr` instead of `./configure` - this will put the files in the right place when you run `make install`

Don't forget that `libheif` relies on `libde265` to decode, and you *may* need to build this from source as well if the latest libheif needs it. See how you go.

**Comment by paddywwoof** [comment]
David, thanks for your help here. I've now tried all those suggestions (compiling libheif is quite long winded on the Raspberry Pi, libde265 even longer!) but still get the same undefined symbol in _libheif_cffi.abi3.so when I try to import pyheif.

Oh well. Maybe I should just tell people they will have to convert their iPhone images to jpeg if they want to display them on the Raspberry Pi. Sooner or later the functionality will be added to PIL

**Comment by david-poirier-csn** [comment]
Sure, no worries. I might try building an `armv6` or `armv7` wheel as I just found out this is possible! This would basically solve all installation issues on ARM.

**Comment by paddywwoof** [comment]
That would be great. Also, looking at issues on the python-pillow site I see that the main (only) contender is pyheif!

**Comment by paddywwoof** [comment]
@david-poirier-csn did building the armv6 or armv7 wheel work? If so, do you have any instructions that could help people with this issue?
Paddy

**Comment by paddywwoof** [comment]
David, for the sake of completion. This has now been fixed https://github.com/pi3d/pi3d_demos/issues/24#issuecomment-733824260 Thanks again for the module.

Paddy
